<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PesertasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pesertas')->delete();
        
        \DB::table('pesertas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 1,
                'urutan' => '1',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            1 => 
            array (
                'id' => 2,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 1,
                'urutan' => '2',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            2 => 
            array (
                'id' => 3,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 1,
                'urutan' => '3',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            3 => 
            array (
                'id' => 4,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 1,
                'urutan' => '4',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            4 => 
            array (
                'id' => 5,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 1,
                'urutan' => '5',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            5 => 
            array (
                'id' => 6,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 1,
                'urutan' => '6',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            6 => 
            array (
                'id' => 7,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 1,
                'urutan' => '7',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            7 => 
            array (
                'id' => 8,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 2,
                'urutan' => '1',
                'nama' => NULL,
                'pendaftaran_id' => 1,
                'user_id' => 8,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-18 08:34:42',
            ),
            8 => 
            array (
                'id' => 9,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 2,
                'urutan' => '2',
                'nama' => NULL,
                'pendaftaran_id' => 2,
                'user_id' => 9,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-18 08:34:42',
            ),
            9 => 
            array (
                'id' => 10,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 2,
                'urutan' => '3',
                'nama' => NULL,
                'pendaftaran_id' => 3,
                'user_id' => 10,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-18 08:34:42',
            ),
            10 => 
            array (
                'id' => 11,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 2,
                'urutan' => '4',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            11 => 
            array (
                'id' => 12,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 2,
                'urutan' => '5',
                'nama' => NULL,
                'pendaftaran_id' => 5,
                'user_id' => 12,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-18 08:47:34',
            ),
            12 => 
            array (
                'id' => 13,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 2,
                'urutan' => '6',
                'nama' => NULL,
                'pendaftaran_id' => 7,
                'user_id' => 14,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-18 08:47:34',
            ),
            13 => 
            array (
                'id' => 14,
                'sesi_id' => 1,
                'location_id' => 1,
                'rotation_id' => 2,
                'urutan' => '7',
                'nama' => NULL,
                'pendaftaran_id' => 4,
                'user_id' => 11,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-18 08:47:34',
            ),
            14 => 
            array (
                'id' => 15,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 3,
                'urutan' => '1',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            15 => 
            array (
                'id' => 16,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 3,
                'urutan' => '2',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            16 => 
            array (
                'id' => 17,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 3,
                'urutan' => '3',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            17 => 
            array (
                'id' => 18,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 3,
                'urutan' => '4',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            18 => 
            array (
                'id' => 19,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 3,
                'urutan' => '5',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            19 => 
            array (
                'id' => 20,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 3,
                'urutan' => '6',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            20 => 
            array (
                'id' => 21,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 3,
                'urutan' => '7',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            21 => 
            array (
                'id' => 22,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 4,
                'urutan' => '1',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            22 => 
            array (
                'id' => 23,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 4,
                'urutan' => '2',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            23 => 
            array (
                'id' => 24,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 4,
                'urutan' => '3',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            24 => 
            array (
                'id' => 25,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 4,
                'urutan' => '4',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            25 => 
            array (
                'id' => 26,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 4,
                'urutan' => '5',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            26 => 
            array (
                'id' => 27,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 4,
                'urutan' => '6',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            27 => 
            array (
                'id' => 28,
                'sesi_id' => 1,
                'location_id' => 2,
                'rotation_id' => 4,
                'urutan' => '7',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:46:33',
                'updated_at' => '2025-04-09 15:46:33',
            ),
            28 => 
            array (
                'id' => 29,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 5,
                'urutan' => '1',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            29 => 
            array (
                'id' => 30,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 5,
                'urutan' => '2',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            30 => 
            array (
                'id' => 31,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 5,
                'urutan' => '3',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            31 => 
            array (
                'id' => 32,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 5,
                'urutan' => '4',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            32 => 
            array (
                'id' => 33,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 5,
                'urutan' => '5',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            33 => 
            array (
                'id' => 34,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 5,
                'urutan' => '6',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            34 => 
            array (
                'id' => 35,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 5,
                'urutan' => '7',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            35 => 
            array (
                'id' => 36,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 6,
                'urutan' => '1',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            36 => 
            array (
                'id' => 37,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 6,
                'urutan' => '2',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            37 => 
            array (
                'id' => 38,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 6,
                'urutan' => '3',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            38 => 
            array (
                'id' => 39,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 6,
                'urutan' => '4',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            39 => 
            array (
                'id' => 40,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 6,
                'urutan' => '5',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            40 => 
            array (
                'id' => 41,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 6,
                'urutan' => '6',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            41 => 
            array (
                'id' => 42,
                'sesi_id' => 2,
                'location_id' => 3,
                'rotation_id' => 6,
                'urutan' => '7',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            42 => 
            array (
                'id' => 43,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 7,
                'urutan' => '1',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            43 => 
            array (
                'id' => 44,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 7,
                'urutan' => '2',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            44 => 
            array (
                'id' => 45,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 7,
                'urutan' => '3',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            45 => 
            array (
                'id' => 46,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 7,
                'urutan' => '4',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            46 => 
            array (
                'id' => 47,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 7,
                'urutan' => '5',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            47 => 
            array (
                'id' => 48,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 7,
                'urutan' => '6',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            48 => 
            array (
                'id' => 49,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 7,
                'urutan' => '7',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            49 => 
            array (
                'id' => 50,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 8,
                'urutan' => '1',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            50 => 
            array (
                'id' => 51,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 8,
                'urutan' => '2',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            51 => 
            array (
                'id' => 52,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 8,
                'urutan' => '3',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            52 => 
            array (
                'id' => 53,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 8,
                'urutan' => '4',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            53 => 
            array (
                'id' => 54,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 8,
                'urutan' => '5',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            54 => 
            array (
                'id' => 55,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 8,
                'urutan' => '6',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
            55 => 
            array (
                'id' => 56,
                'sesi_id' => 2,
                'location_id' => 4,
                'rotation_id' => 8,
                'urutan' => '7',
                'nama' => NULL,
                'pendaftaran_id' => NULL,
                'user_id' => NULL,
                'status' => NULL,
                'created_at' => '2025-04-09 15:47:32',
                'updated_at' => '2025-04-09 15:47:32',
            ),
        ));
        
        
    }
}