<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RubriksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rubriks')->delete();
        
        \DB::table('rubriks')->insert(array (
            0 => 
            array (
                'id' => 1,
                'template_id' => 1,
                'urutan' => 1,
                'Nilai_0' => '<p>Peserta ujian<b> tidak</b> memfasilitasi pasien untuk menceritakan kesakitannya.</p>',
                'Nilai_1' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya <b>namun sebagian besar&nbsp; pertanyaan tidak</b>&nbsp; mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>&nbsp;<br><b>Atau </b><br>Melakukan anamnesis secara tidak lengkap atau tidak relevan<br><br></p>',
                'Nilai_2' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya, <b>namun sebagian kecil&nbsp; pertanyaan tidak</b> mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br><br><br></p>',
                'Nilai_3' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya dengan&nbsp; pertanyaan-pertanyaan yang sesuai dengan keluhan pasien untuk mendapatkan informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br>3. RP SOS : Begadang<br><br></p>',
                'aktif0' => 1,
                'aktif1' => 1,
                'aktif2' => 1,
                'aktif3' => 1,
                'bobot' => 1,
                'created_at' => '2025-03-27 07:11:39',
                'updated_at' => '2025-03-27 07:11:39',
            ),
            1 => 
            array (
                'id' => 2,
                'template_id' => 1,
                'urutan' => 2,
                'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
                'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
                'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
            'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
            'aktif0' => 1,
            'aktif1' => 1,
            'aktif2' => 1,
            'aktif3' => 1,
            'bobot' => 1,
            'created_at' => '2025-03-27 07:11:39',
            'updated_at' => '2025-03-27 07:11:39',
        ),
        2 => 
        array (
            'id' => 3,
            'template_id' => 1,
            'urutan' => 3,
            'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
            'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
            'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
        'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
        'aktif0' => 1,
        'aktif1' => 1,
        'aktif2' => 1,
        'aktif3' => 1,
        'bobot' => 1,
        'created_at' => '2025-03-27 07:11:39',
        'updated_at' => '2025-03-27 07:11:39',
    ),
    3 => 
    array (
        'id' => 4,
        'template_id' => 1,
        'urutan' => 4,
        'Nilai_0' => '<p>Peserta ujian tidak mengusulkan tes/prosedur masalah klinik pasien</p>',
        'Nilai_1' => '<p>Peserta ujian mengusulkan&nbsp; tes/prosedur tidak sesuai masalah klinik pasien</p>',
        'Nilai_2' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tidak tepat <br></p>',
        'Nilai_3' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tepat <br><br><b>Pemeriksaan Laboratorium : dalam batas normal<br>CT Scan kepala : dalam batas normal</b><br><br></p>',
        'aktif0' => 1,
        'aktif1' => 1,
        'aktif2' => 1,
        'aktif3' => 1,
        'bobot' => 1,
        'created_at' => '2025-03-27 07:11:39',
        'updated_at' => '2025-03-27 07:11:39',
    ),
    4 => 
    array (
        'id' => 5,
        'template_id' => 1,
        'urutan' => 5,
        'Nilai_0' => '<p>Peserta ujian tidak dapat menentukan diagnosis kerja dan diagnosis banding</p>',
        'Nilai_1' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja sebagai diagnosis banding<br><br><b>ATAU </b><br><br>Peserta ujian menetapkan dengan menuliskan diagnosis kerja<br><br></p>',
        'Nilai_2' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja dan 1 diagnosis banding</p>',
    'Nilai_3' => '<p>Peserta ujian menetapkan dengan menuliskan 1 diagnosis kerja dan 2 diagnosis banding yang lengkap, sesuai dengan masalah klinik pasien<br><br><b>•&nbsp;&nbsp;&nbsp; Diagnosis: BPPV (Benign Paroxismal Positional Vertigo)</b><br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 1: Neuritis vestibuler<br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 2: Meniere’s disease<br><br></p>',
        'aktif0' => 1,
        'aktif1' => 1,
        'aktif2' => 1,
        'aktif3' => 1,
        'bobot' => 1,
        'created_at' => '2025-03-27 07:11:39',
        'updated_at' => '2025-03-27 07:11:39',
    ),
    5 => 
    array (
        'id' => 6,
        'template_id' => 1,
        'urutan' => 6,
        'Nilai_0' => '<p>Peserta ujian tidak melakukan tindakan <br>Atau<br>melakukan tetapi tidak sesuai perintah<br>Atau<br>melakukan tetapi tidak sesuai masalah klinik pasien<br><br></p>',
        'Nilai_1' => '<p>Peserta ujian melakukan tindakan yang sesuai perintah atau masalah klinik pasien tetapi tidak lengkap<br><br>Dan Atau <br><br>Tidak menerapkan prinsip septik/ aseptic<br><br></p>',
        'Nilai_2' => '<p>Peserta ujian melakukan tindakan yang sesuai masalah klinik pasien, lengkap<br>Tetapi tidak urut dan sistematik<br><br></p>',
    'Nilai_3' => '<p>Peserta ujian melakukan tatalaksana non farmakoterapi yang sesuai masalah klinik pasien, lengkap, urut dan sistematik<br><br><b>ATAU</b><br><br>Peserta menyampaikan rencana tatalaksana non farmakoterapi <br><br><b>Non Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Epley Maneuver :<br>•&nbsp;&nbsp;&nbsp; Pasien dilakukan latihan vestibular (vestibular exercise) dengan metode brandDaroff.<br>•&nbsp;&nbsp;&nbsp; Pasien duduk tegak di pinggir tempat tidur dengan kedua tungkai tergantung, dengan kedua mata tertutup baringkan tubuh dengan cepat ke salah satu sisi, pertahankan selama 30 detik. Setelah itu duduk kembali. Setelah 30 detik, baringkan dengan cepat ke sisi lain. Pertahankan selama 30 detik, lalu duduk kembali. Lakukan latihan ini 3 kali pada pagi, siang dan malam hari masing-masing diulang 5 kali serta dilakukan selama 2 minggu atau 3 minggu dengan latihan pagi dan sore hari<br><br><br></p>',
        'aktif0' => 1,
        'aktif1' => 1,
        'aktif2' => 1,
        'aktif3' => 1,
        'bobot' => 1,
        'created_at' => '2025-03-27 07:11:39',
        'updated_at' => '2025-03-27 07:11:39',
    ),
    6 => 
    array (
        'id' => 7,
        'template_id' => 1,
        'urutan' => 7,
        'Nilai_0' => '<p>Peserta ujian tidak memberikan tatalaksana farmakoterapi pada pasien</p>',
        'Nilai_1' => '<p>Peserta ujian memilih obat dengan&nbsp; menerapkan <b>beberapa</b>&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br></p>',
        'Nilai_2' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br>TETAPI&nbsp; menuliskan resep tidak&nbsp; lengkap<br><br></p>',
        'Nilai_3' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br>DAN<br>•&nbsp;&nbsp;&nbsp; menuliskan resep dengan lengkap dan benar.<br><br><b>Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Betahistin tablet 3x6 mg, per oral DAN <br>•&nbsp;&nbsp;&nbsp; Flunarizin tab 2x5 mg<b> DAN</b><br>•&nbsp;&nbsp;&nbsp; Domperidon <b>10 mg 3x1 tab atau</b> Ondansetron 2 x 2mg <br><br><b>Penulisan resep</b><br>R/ Betahistin tab&nbsp; 6 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN<br><br>R/ Ondansetron tab 2 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br>ATAU<br><br>R/ Domperidon tab 10 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN <br><br>R/ Flunarizine tab 5 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br><br><br><br><br>Pro : Tn. X<br>Usia : 40 Tahun<br>Alamat : Cirebon<br><br></p>',
        'aktif0' => 1,
        'aktif1' => 1,
        'aktif2' => 1,
        'aktif3' => 1,
        'bobot' => 1,
        'created_at' => '2025-03-27 07:11:39',
        'updated_at' => '2025-03-27 07:11:39',
    ),
    7 => 
    array (
        'id' => 8,
        'template_id' => 1,
        'urutan' => 8,
        'Nilai_0' => '<p>Peserta ujian sama sekali tidak melakukan komunikasi dan edukasi</p>',
        'Nilai_1' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>salah satu</b> prinsip komunikasi dan edukasi <br><br><br></p>',
        'Nilai_2' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> point dari&nbsp; prinsip komunikasi dan 2 point dari 3 poin edukasi</p>',
    'Nilai_3' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; mampu membina hubungan baik dengan pasien secara verbal non verbal (ramah, terbuka, kontak mata, salam, empati dan hubungan komunikasi dua arah, respon)<br>2.&nbsp;&nbsp;&nbsp; mampu memberikan kesempatan pasien untuk bercerita dan mengarahkan cerita<br>3.&nbsp;&nbsp;&nbsp; mampu untuk melibatkan pasien dalam membuat keputusan klinik, pemeriksaan klinik. <br>4.&nbsp;&nbsp;&nbsp; mampu memberikan penyuluhan yang isinya sesuai dengan masalah&nbsp; pasien <br><br><b>Edukasi :</b><br>1.&nbsp;&nbsp;&nbsp; Penjelasan mengenai penyakit<br>2.&nbsp;&nbsp;&nbsp; Penjelasan mengenai tatacara minum obat<br>3.&nbsp;&nbsp;&nbsp; Penjelasan mengenai pencegahan : Hindari mengubah posisi kepala secara mendadak dan jangan menolehkan kepala pada satu sisi dengan terlalu lama. Lakukan latihan rutin untuk BPPV (manuver epley). Lakukan olahraga rutin, minimal 30 menit setiap hari. Terapkan pola hidup sehat, serta istirahat dan tidur yang cukup. Hindari factor pencetus : kurang tidur<br><br></p>',
        'aktif0' => 1,
        'aktif1' => 1,
        'aktif2' => 1,
        'aktif3' => 1,
        'bobot' => 1,
        'created_at' => '2025-03-27 07:11:39',
        'updated_at' => '2025-03-27 07:11:39',
    ),
    8 => 
    array (
        'id' => 9,
        'template_id' => 1,
        'urutan' => 9,
        'Nilai_0' => '<p>Peserta ujian tidak meminta izin secara lisan dan sama sekali<b> tidak </b>menunjukkan perilaku profesional</p>',
        'Nilai_1' => '<p>Meminta izin secara lisan dan menunjukkan <b>1 poin</b> perilaku profesional</p>',
        'Nilai_2' => '<p>Meminta izin secara lisan<b> dan</b> menunjukkan <b>2-3 poin </b>perilaku profesional</p>',
    'Nilai_3' => '<p>Meminta izin secara lisan dan melakukan di bawah ini secara<b> lengkap:</b><br>1.&nbsp;&nbsp;&nbsp; Menerapkan prinsip Patient Safety (cuci tangan sebelum dan sesudah melakukan pemeriksaan, melakukan setiap tindakan dengan berhati-hati dan teliti sehingga tidak membahayakan pasien dan diri sendiri, memastikan identitas pasien)<br>2.&nbsp;&nbsp;&nbsp; memperhatikan kenyamanan pasien <br>3.&nbsp;&nbsp;&nbsp; menunjukan rasa hormat kepada pasien<br>4.&nbsp;&nbsp;&nbsp; mengetahui keterbatasan dengan merujuk&nbsp; atau melakukan konsultasi bila diperlukan<br><br></p>',
        'aktif0' => 1,
        'aktif1' => 1,
        'aktif2' => 1,
        'aktif3' => 1,
        'bobot' => 1,
        'created_at' => '2025-03-27 07:11:39',
        'updated_at' => '2025-03-27 07:11:39',
    ),
    9 => 
    array (
        'id' => 10,
        'template_id' => 2,
        'urutan' => 1,
        'Nilai_0' => '<p>Peserta ujian<b> tidak</b> memfasilitasi pasien untuk menceritakan kesakitannya.</p>',
        'Nilai_1' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya <b>namun sebagian besar&nbsp; pertanyaan tidak</b>&nbsp; mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>&nbsp;<br><b>Atau </b><br>Melakukan anamnesis secara tidak lengkap atau tidak relevan<br><br></p>',
        'Nilai_2' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya, <b>namun sebagian kecil&nbsp; pertanyaan tidak</b> mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br><br><br></p>',
        'Nilai_3' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya dengan&nbsp; pertanyaan-pertanyaan yang sesuai dengan keluhan pasien untuk mendapatkan informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br>3. RP SOS : Begadang<br><br></p>',
        'aktif0' => 1,
        'aktif1' => 1,
        'aktif2' => 1,
        'aktif3' => 1,
        'bobot' => 1,
        'created_at' => '2025-03-27 07:24:01',
        'updated_at' => '2025-03-27 07:24:01',
    ),
    10 => 
    array (
        'id' => 11,
        'template_id' => 2,
        'urutan' => 2,
        'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
        'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
        'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
    'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
    'aktif0' => 1,
    'aktif1' => 1,
    'aktif2' => 1,
    'aktif3' => 1,
    'bobot' => 1,
    'created_at' => '2025-03-27 07:24:01',
    'updated_at' => '2025-03-27 07:24:01',
),
11 => 
array (
    'id' => 12,
    'template_id' => 2,
    'urutan' => 3,
    'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
    'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
    'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:24:01',
'updated_at' => '2025-03-27 07:24:01',
),
12 => 
array (
'id' => 13,
'template_id' => 2,
'urutan' => 4,
'Nilai_0' => '<p>Peserta ujian tidak mengusulkan tes/prosedur masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian mengusulkan&nbsp; tes/prosedur tidak sesuai masalah klinik pasien</p>',
'Nilai_2' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tidak tepat <br></p>',
'Nilai_3' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tepat <br><br><b>Pemeriksaan Laboratorium : dalam batas normal<br>CT Scan kepala : dalam batas normal</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:24:01',
'updated_at' => '2025-03-27 07:24:01',
),
13 => 
array (
'id' => 14,
'template_id' => 2,
'urutan' => 5,
'Nilai_0' => '<p>Peserta ujian tidak dapat menentukan diagnosis kerja dan diagnosis banding</p>',
'Nilai_1' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja sebagai diagnosis banding<br><br><b>ATAU </b><br><br>Peserta ujian menetapkan dengan menuliskan diagnosis kerja<br><br></p>',
'Nilai_2' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja dan 1 diagnosis banding</p>',
'Nilai_3' => '<p>Peserta ujian menetapkan dengan menuliskan 1 diagnosis kerja dan 2 diagnosis banding yang lengkap, sesuai dengan masalah klinik pasien<br><br><b>•&nbsp;&nbsp;&nbsp; Diagnosis: BPPV (Benign Paroxismal Positional Vertigo)</b><br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 1: Neuritis vestibuler<br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 2: Meniere’s disease<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:24:01',
'updated_at' => '2025-03-27 07:24:01',
),
14 => 
array (
'id' => 15,
'template_id' => 2,
'urutan' => 6,
'Nilai_0' => '<p>Peserta ujian tidak melakukan tindakan <br>Atau<br>melakukan tetapi tidak sesuai perintah<br>Atau<br>melakukan tetapi tidak sesuai masalah klinik pasien<br><br></p>',
'Nilai_1' => '<p>Peserta ujian melakukan tindakan yang sesuai perintah atau masalah klinik pasien tetapi tidak lengkap<br><br>Dan Atau <br><br>Tidak menerapkan prinsip septik/ aseptic<br><br></p>',
'Nilai_2' => '<p>Peserta ujian melakukan tindakan yang sesuai masalah klinik pasien, lengkap<br>Tetapi tidak urut dan sistematik<br><br></p>',
'Nilai_3' => '<p>Peserta ujian melakukan tatalaksana non farmakoterapi yang sesuai masalah klinik pasien, lengkap, urut dan sistematik<br><br><b>ATAU</b><br><br>Peserta menyampaikan rencana tatalaksana non farmakoterapi <br><br><b>Non Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Epley Maneuver :<br>•&nbsp;&nbsp;&nbsp; Pasien dilakukan latihan vestibular (vestibular exercise) dengan metode brandDaroff.<br>•&nbsp;&nbsp;&nbsp; Pasien duduk tegak di pinggir tempat tidur dengan kedua tungkai tergantung, dengan kedua mata tertutup baringkan tubuh dengan cepat ke salah satu sisi, pertahankan selama 30 detik. Setelah itu duduk kembali. Setelah 30 detik, baringkan dengan cepat ke sisi lain. Pertahankan selama 30 detik, lalu duduk kembali. Lakukan latihan ini 3 kali pada pagi, siang dan malam hari masing-masing diulang 5 kali serta dilakukan selama 2 minggu atau 3 minggu dengan latihan pagi dan sore hari<br><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:24:01',
'updated_at' => '2025-03-27 07:24:01',
),
15 => 
array (
'id' => 16,
'template_id' => 2,
'urutan' => 7,
'Nilai_0' => '<p>Peserta ujian tidak memberikan tatalaksana farmakoterapi pada pasien</p>',
'Nilai_1' => '<p>Peserta ujian memilih obat dengan&nbsp; menerapkan <b>beberapa</b>&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br>TETAPI&nbsp; menuliskan resep tidak&nbsp; lengkap<br><br></p>',
'Nilai_3' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br>DAN<br>•&nbsp;&nbsp;&nbsp; menuliskan resep dengan lengkap dan benar.<br><br><b>Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Betahistin tablet 3x6 mg, per oral DAN <br>•&nbsp;&nbsp;&nbsp; Flunarizin tab 2x5 mg<b> DAN</b><br>•&nbsp;&nbsp;&nbsp; Domperidon <b>10 mg 3x1 tab atau</b> Ondansetron 2 x 2mg <br><br><b>Penulisan resep</b><br>R/ Betahistin tab&nbsp; 6 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN<br><br>R/ Ondansetron tab 2 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br>ATAU<br><br>R/ Domperidon tab 10 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN <br><br>R/ Flunarizine tab 5 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br><br><br><br><br>Pro : Tn. X<br>Usia : 40 Tahun<br>Alamat : Cirebon<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:24:01',
'updated_at' => '2025-03-27 07:24:01',
),
16 => 
array (
'id' => 17,
'template_id' => 2,
'urutan' => 8,
'Nilai_0' => '<p>Peserta ujian sama sekali tidak melakukan komunikasi dan edukasi</p>',
'Nilai_1' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>salah satu</b> prinsip komunikasi dan edukasi <br><br><br></p>',
'Nilai_2' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> point dari&nbsp; prinsip komunikasi dan 2 point dari 3 poin edukasi</p>',
'Nilai_3' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; mampu membina hubungan baik dengan pasien secara verbal non verbal (ramah, terbuka, kontak mata, salam, empati dan hubungan komunikasi dua arah, respon)<br>2.&nbsp;&nbsp;&nbsp; mampu memberikan kesempatan pasien untuk bercerita dan mengarahkan cerita<br>3.&nbsp;&nbsp;&nbsp; mampu untuk melibatkan pasien dalam membuat keputusan klinik, pemeriksaan klinik. <br>4.&nbsp;&nbsp;&nbsp; mampu memberikan penyuluhan yang isinya sesuai dengan masalah&nbsp; pasien <br><br><b>Edukasi :</b><br>1.&nbsp;&nbsp;&nbsp; Penjelasan mengenai penyakit<br>2.&nbsp;&nbsp;&nbsp; Penjelasan mengenai tatacara minum obat<br>3.&nbsp;&nbsp;&nbsp; Penjelasan mengenai pencegahan : Hindari mengubah posisi kepala secara mendadak dan jangan menolehkan kepala pada satu sisi dengan terlalu lama. Lakukan latihan rutin untuk BPPV (manuver epley). Lakukan olahraga rutin, minimal 30 menit setiap hari. Terapkan pola hidup sehat, serta istirahat dan tidur yang cukup. Hindari factor pencetus : kurang tidur<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:24:01',
'updated_at' => '2025-03-27 07:24:01',
),
17 => 
array (
'id' => 18,
'template_id' => 2,
'urutan' => 9,
'Nilai_0' => '<p>Peserta ujian tidak meminta izin secara lisan dan sama sekali<b> tidak </b>menunjukkan perilaku profesional</p>',
'Nilai_1' => '<p>Meminta izin secara lisan dan menunjukkan <b>1 poin</b> perilaku profesional</p>',
'Nilai_2' => '<p>Meminta izin secara lisan<b> dan</b> menunjukkan <b>2-3 poin </b>perilaku profesional</p>',
'Nilai_3' => '<p>Meminta izin secara lisan dan melakukan di bawah ini secara<b> lengkap:</b><br>1.&nbsp;&nbsp;&nbsp; Menerapkan prinsip Patient Safety (cuci tangan sebelum dan sesudah melakukan pemeriksaan, melakukan setiap tindakan dengan berhati-hati dan teliti sehingga tidak membahayakan pasien dan diri sendiri, memastikan identitas pasien)<br>2.&nbsp;&nbsp;&nbsp; memperhatikan kenyamanan pasien <br>3.&nbsp;&nbsp;&nbsp; menunjukan rasa hormat kepada pasien<br>4.&nbsp;&nbsp;&nbsp; mengetahui keterbatasan dengan merujuk&nbsp; atau melakukan konsultasi bila diperlukan<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:24:01',
'updated_at' => '2025-03-27 07:24:01',
),
18 => 
array (
'id' => 19,
'template_id' => 3,
'urutan' => 1,
'Nilai_0' => '<p>Peserta ujian<b> tidak</b> memfasilitasi pasien untuk menceritakan kesakitannya.</p>',
'Nilai_1' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya <b>namun sebagian besar&nbsp; pertanyaan tidak</b>&nbsp; mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>&nbsp;<br><b>Atau </b><br>Melakukan anamnesis secara tidak lengkap atau tidak relevan<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya, <b>namun sebagian kecil&nbsp; pertanyaan tidak</b> mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br><br><br></p>',
'Nilai_3' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya dengan&nbsp; pertanyaan-pertanyaan yang sesuai dengan keluhan pasien untuk mendapatkan informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br>3. RP SOS : Begadang<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
19 => 
array (
'id' => 20,
'template_id' => 3,
'urutan' => 2,
'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
20 => 
array (
'id' => 21,
'template_id' => 3,
'urutan' => 3,
'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
21 => 
array (
'id' => 22,
'template_id' => 3,
'urutan' => 4,
'Nilai_0' => '<p>Peserta ujian tidak mengusulkan tes/prosedur masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian mengusulkan&nbsp; tes/prosedur tidak sesuai masalah klinik pasien</p>',
'Nilai_2' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tidak tepat <br></p>',
'Nilai_3' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tepat <br><br><b>Pemeriksaan Laboratorium : dalam batas normal<br>CT Scan kepala : dalam batas normal</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
22 => 
array (
'id' => 23,
'template_id' => 3,
'urutan' => 5,
'Nilai_0' => '<p>Peserta ujian tidak dapat menentukan diagnosis kerja dan diagnosis banding</p>',
'Nilai_1' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja sebagai diagnosis banding<br><br><b>ATAU </b><br><br>Peserta ujian menetapkan dengan menuliskan diagnosis kerja<br><br></p>',
'Nilai_2' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja dan 1 diagnosis banding</p>',
'Nilai_3' => '<p>Peserta ujian menetapkan dengan menuliskan 1 diagnosis kerja dan 2 diagnosis banding yang lengkap, sesuai dengan masalah klinik pasien<br><br><b>•&nbsp;&nbsp;&nbsp; Diagnosis: BPPV (Benign Paroxismal Positional Vertigo)</b><br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 1: Neuritis vestibuler<br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 2: Meniere’s disease<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
23 => 
array (
'id' => 24,
'template_id' => 3,
'urutan' => 6,
'Nilai_0' => '<p>Peserta ujian tidak melakukan tindakan <br>Atau<br>melakukan tetapi tidak sesuai perintah<br>Atau<br>melakukan tetapi tidak sesuai masalah klinik pasien<br><br></p>',
'Nilai_1' => '<p>Peserta ujian melakukan tindakan yang sesuai perintah atau masalah klinik pasien tetapi tidak lengkap<br><br>Dan Atau <br><br>Tidak menerapkan prinsip septik/ aseptic<br><br></p>',
'Nilai_2' => '<p>Peserta ujian melakukan tindakan yang sesuai masalah klinik pasien, lengkap<br>Tetapi tidak urut dan sistematik<br><br></p>',
'Nilai_3' => '<p>Peserta ujian melakukan tatalaksana non farmakoterapi yang sesuai masalah klinik pasien, lengkap, urut dan sistematik<br><br><b>ATAU</b><br><br>Peserta menyampaikan rencana tatalaksana non farmakoterapi <br><br><b>Non Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Epley Maneuver :<br>•&nbsp;&nbsp;&nbsp; Pasien dilakukan latihan vestibular (vestibular exercise) dengan metode brandDaroff.<br>•&nbsp;&nbsp;&nbsp; Pasien duduk tegak di pinggir tempat tidur dengan kedua tungkai tergantung, dengan kedua mata tertutup baringkan tubuh dengan cepat ke salah satu sisi, pertahankan selama 30 detik. Setelah itu duduk kembali. Setelah 30 detik, baringkan dengan cepat ke sisi lain. Pertahankan selama 30 detik, lalu duduk kembali. Lakukan latihan ini 3 kali pada pagi, siang dan malam hari masing-masing diulang 5 kali serta dilakukan selama 2 minggu atau 3 minggu dengan latihan pagi dan sore hari<br><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
24 => 
array (
'id' => 25,
'template_id' => 3,
'urutan' => 7,
'Nilai_0' => '<p>Peserta ujian tidak memberikan tatalaksana farmakoterapi pada pasien</p>',
'Nilai_1' => '<p>Peserta ujian memilih obat dengan&nbsp; menerapkan <b>beberapa</b>&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br>TETAPI&nbsp; menuliskan resep tidak&nbsp; lengkap<br><br></p>',
'Nilai_3' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br>DAN<br>•&nbsp;&nbsp;&nbsp; menuliskan resep dengan lengkap dan benar.<br><br><b>Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Betahistin tablet 3x6 mg, per oral DAN <br>•&nbsp;&nbsp;&nbsp; Flunarizin tab 2x5 mg<b> DAN</b><br>•&nbsp;&nbsp;&nbsp; Domperidon <b>10 mg 3x1 tab atau</b> Ondansetron 2 x 2mg <br><br><b>Penulisan resep</b><br>R/ Betahistin tab&nbsp; 6 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN<br><br>R/ Ondansetron tab 2 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br>ATAU<br><br>R/ Domperidon tab 10 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN <br><br>R/ Flunarizine tab 5 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br><br><br><br><br>Pro : Tn. X<br>Usia : 40 Tahun<br>Alamat : Cirebon<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
25 => 
array (
'id' => 26,
'template_id' => 3,
'urutan' => 8,
'Nilai_0' => '<p>Peserta ujian sama sekali tidak melakukan komunikasi dan edukasi</p>',
'Nilai_1' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>salah satu</b> prinsip komunikasi dan edukasi <br><br><br></p>',
'Nilai_2' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> point dari&nbsp; prinsip komunikasi dan 2 point dari 3 poin edukasi</p>',
'Nilai_3' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; mampu membina hubungan baik dengan pasien secara verbal non verbal (ramah, terbuka, kontak mata, salam, empati dan hubungan komunikasi dua arah, respon)<br>2.&nbsp;&nbsp;&nbsp; mampu memberikan kesempatan pasien untuk bercerita dan mengarahkan cerita<br>3.&nbsp;&nbsp;&nbsp; mampu untuk melibatkan pasien dalam membuat keputusan klinik, pemeriksaan klinik. <br>4.&nbsp;&nbsp;&nbsp; mampu memberikan penyuluhan yang isinya sesuai dengan masalah&nbsp; pasien <br><br><b>Edukasi :</b><br>1.&nbsp;&nbsp;&nbsp; Penjelasan mengenai penyakit<br>2.&nbsp;&nbsp;&nbsp; Penjelasan mengenai tatacara minum obat<br>3.&nbsp;&nbsp;&nbsp; Penjelasan mengenai pencegahan : Hindari mengubah posisi kepala secara mendadak dan jangan menolehkan kepala pada satu sisi dengan terlalu lama. Lakukan latihan rutin untuk BPPV (manuver epley). Lakukan olahraga rutin, minimal 30 menit setiap hari. Terapkan pola hidup sehat, serta istirahat dan tidur yang cukup. Hindari factor pencetus : kurang tidur<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
26 => 
array (
'id' => 27,
'template_id' => 3,
'urutan' => 9,
'Nilai_0' => '<p>Peserta ujian tidak meminta izin secara lisan dan sama sekali<b> tidak </b>menunjukkan perilaku profesional</p>',
'Nilai_1' => '<p>Meminta izin secara lisan dan menunjukkan <b>1 poin</b> perilaku profesional</p>',
'Nilai_2' => '<p>Meminta izin secara lisan<b> dan</b> menunjukkan <b>2-3 poin </b>perilaku profesional</p>',
'Nilai_3' => '<p>Meminta izin secara lisan dan melakukan di bawah ini secara<b> lengkap:</b><br>1.&nbsp;&nbsp;&nbsp; Menerapkan prinsip Patient Safety (cuci tangan sebelum dan sesudah melakukan pemeriksaan, melakukan setiap tindakan dengan berhati-hati dan teliti sehingga tidak membahayakan pasien dan diri sendiri, memastikan identitas pasien)<br>2.&nbsp;&nbsp;&nbsp; memperhatikan kenyamanan pasien <br>3.&nbsp;&nbsp;&nbsp; menunjukan rasa hormat kepada pasien<br>4.&nbsp;&nbsp;&nbsp; mengetahui keterbatasan dengan merujuk&nbsp; atau melakukan konsultasi bila diperlukan<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:25:52',
'updated_at' => '2025-03-27 07:25:52',
),
27 => 
array (
'id' => 28,
'template_id' => 4,
'urutan' => 1,
'Nilai_0' => '<p>Peserta ujian<b> tidak</b> memfasilitasi pasien untuk menceritakan kesakitannya.</p>',
'Nilai_1' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya <b>namun sebagian besar&nbsp; pertanyaan tidak</b>&nbsp; mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>&nbsp;<br><b>Atau </b><br>Melakukan anamnesis secara tidak lengkap atau tidak relevan<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya, <b>namun sebagian kecil&nbsp; pertanyaan tidak</b> mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br><br><br></p>',
'Nilai_3' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya dengan&nbsp; pertanyaan-pertanyaan yang sesuai dengan keluhan pasien untuk mendapatkan informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br>3. RP SOS : Begadang<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
28 => 
array (
'id' => 29,
'template_id' => 4,
'urutan' => 2,
'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
29 => 
array (
'id' => 30,
'template_id' => 4,
'urutan' => 3,
'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
30 => 
array (
'id' => 31,
'template_id' => 4,
'urutan' => 4,
'Nilai_0' => '<p>Peserta ujian tidak mengusulkan tes/prosedur masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian mengusulkan&nbsp; tes/prosedur tidak sesuai masalah klinik pasien</p>',
'Nilai_2' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tidak tepat <br></p>',
'Nilai_3' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tepat <br><br><b>Pemeriksaan Laboratorium : dalam batas normal<br>CT Scan kepala : dalam batas normal</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
31 => 
array (
'id' => 32,
'template_id' => 4,
'urutan' => 5,
'Nilai_0' => '<p>Peserta ujian tidak dapat menentukan diagnosis kerja dan diagnosis banding</p>',
'Nilai_1' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja sebagai diagnosis banding<br><br><b>ATAU </b><br><br>Peserta ujian menetapkan dengan menuliskan diagnosis kerja<br><br></p>',
'Nilai_2' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja dan 1 diagnosis banding</p>',
'Nilai_3' => '<p>Peserta ujian menetapkan dengan menuliskan 1 diagnosis kerja dan 2 diagnosis banding yang lengkap, sesuai dengan masalah klinik pasien<br><br><b>•&nbsp;&nbsp;&nbsp; Diagnosis: BPPV (Benign Paroxismal Positional Vertigo)</b><br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 1: Neuritis vestibuler<br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 2: Meniere’s disease<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
32 => 
array (
'id' => 33,
'template_id' => 4,
'urutan' => 6,
'Nilai_0' => '<p>Peserta ujian tidak melakukan tindakan <br>Atau<br>melakukan tetapi tidak sesuai perintah<br>Atau<br>melakukan tetapi tidak sesuai masalah klinik pasien<br><br></p>',
'Nilai_1' => '<p>Peserta ujian melakukan tindakan yang sesuai perintah atau masalah klinik pasien tetapi tidak lengkap<br><br>Dan Atau <br><br>Tidak menerapkan prinsip septik/ aseptic<br><br></p>',
'Nilai_2' => '<p>Peserta ujian melakukan tindakan yang sesuai masalah klinik pasien, lengkap<br>Tetapi tidak urut dan sistematik<br><br></p>',
'Nilai_3' => '<p>Peserta ujian melakukan tatalaksana non farmakoterapi yang sesuai masalah klinik pasien, lengkap, urut dan sistematik<br><br><b>ATAU</b><br><br>Peserta menyampaikan rencana tatalaksana non farmakoterapi <br><br><b>Non Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Epley Maneuver :<br>•&nbsp;&nbsp;&nbsp; Pasien dilakukan latihan vestibular (vestibular exercise) dengan metode brandDaroff.<br>•&nbsp;&nbsp;&nbsp; Pasien duduk tegak di pinggir tempat tidur dengan kedua tungkai tergantung, dengan kedua mata tertutup baringkan tubuh dengan cepat ke salah satu sisi, pertahankan selama 30 detik. Setelah itu duduk kembali. Setelah 30 detik, baringkan dengan cepat ke sisi lain. Pertahankan selama 30 detik, lalu duduk kembali. Lakukan latihan ini 3 kali pada pagi, siang dan malam hari masing-masing diulang 5 kali serta dilakukan selama 2 minggu atau 3 minggu dengan latihan pagi dan sore hari<br><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
33 => 
array (
'id' => 34,
'template_id' => 4,
'urutan' => 7,
'Nilai_0' => '<p>Peserta ujian tidak memberikan tatalaksana farmakoterapi pada pasien</p>',
'Nilai_1' => '<p>Peserta ujian memilih obat dengan&nbsp; menerapkan <b>beberapa</b>&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br>TETAPI&nbsp; menuliskan resep tidak&nbsp; lengkap<br><br></p>',
'Nilai_3' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br>DAN<br>•&nbsp;&nbsp;&nbsp; menuliskan resep dengan lengkap dan benar.<br><br><b>Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Betahistin tablet 3x6 mg, per oral DAN <br>•&nbsp;&nbsp;&nbsp; Flunarizin tab 2x5 mg<b> DAN</b><br>•&nbsp;&nbsp;&nbsp; Domperidon <b>10 mg 3x1 tab atau</b> Ondansetron 2 x 2mg <br><br><b>Penulisan resep</b><br>R/ Betahistin tab&nbsp; 6 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN<br><br>R/ Ondansetron tab 2 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br>ATAU<br><br>R/ Domperidon tab 10 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN <br><br>R/ Flunarizine tab 5 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br><br><br><br><br>Pro : Tn. X<br>Usia : 40 Tahun<br>Alamat : Cirebon<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
34 => 
array (
'id' => 35,
'template_id' => 4,
'urutan' => 8,
'Nilai_0' => '<p>Peserta ujian sama sekali tidak melakukan komunikasi dan edukasi</p>',
'Nilai_1' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>salah satu</b> prinsip komunikasi dan edukasi <br><br><br></p>',
'Nilai_2' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> point dari&nbsp; prinsip komunikasi dan 2 point dari 3 poin edukasi</p>',
'Nilai_3' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; mampu membina hubungan baik dengan pasien secara verbal non verbal (ramah, terbuka, kontak mata, salam, empati dan hubungan komunikasi dua arah, respon)<br>2.&nbsp;&nbsp;&nbsp; mampu memberikan kesempatan pasien untuk bercerita dan mengarahkan cerita<br>3.&nbsp;&nbsp;&nbsp; mampu untuk melibatkan pasien dalam membuat keputusan klinik, pemeriksaan klinik. <br>4.&nbsp;&nbsp;&nbsp; mampu memberikan penyuluhan yang isinya sesuai dengan masalah&nbsp; pasien <br><br><b>Edukasi :</b><br>1.&nbsp;&nbsp;&nbsp; Penjelasan mengenai penyakit<br>2.&nbsp;&nbsp;&nbsp; Penjelasan mengenai tatacara minum obat<br>3.&nbsp;&nbsp;&nbsp; Penjelasan mengenai pencegahan : Hindari mengubah posisi kepala secara mendadak dan jangan menolehkan kepala pada satu sisi dengan terlalu lama. Lakukan latihan rutin untuk BPPV (manuver epley). Lakukan olahraga rutin, minimal 30 menit setiap hari. Terapkan pola hidup sehat, serta istirahat dan tidur yang cukup. Hindari factor pencetus : kurang tidur<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
35 => 
array (
'id' => 36,
'template_id' => 4,
'urutan' => 9,
'Nilai_0' => '<p>Peserta ujian tidak meminta izin secara lisan dan sama sekali<b> tidak </b>menunjukkan perilaku profesional</p>',
'Nilai_1' => '<p>Meminta izin secara lisan dan menunjukkan <b>1 poin</b> perilaku profesional</p>',
'Nilai_2' => '<p>Meminta izin secara lisan<b> dan</b> menunjukkan <b>2-3 poin </b>perilaku profesional</p>',
'Nilai_3' => '<p>Meminta izin secara lisan dan melakukan di bawah ini secara<b> lengkap:</b><br>1.&nbsp;&nbsp;&nbsp; Menerapkan prinsip Patient Safety (cuci tangan sebelum dan sesudah melakukan pemeriksaan, melakukan setiap tindakan dengan berhati-hati dan teliti sehingga tidak membahayakan pasien dan diri sendiri, memastikan identitas pasien)<br>2.&nbsp;&nbsp;&nbsp; memperhatikan kenyamanan pasien <br>3.&nbsp;&nbsp;&nbsp; menunjukan rasa hormat kepada pasien<br>4.&nbsp;&nbsp;&nbsp; mengetahui keterbatasan dengan merujuk&nbsp; atau melakukan konsultasi bila diperlukan<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:21',
'updated_at' => '2025-03-27 07:26:21',
),
36 => 
array (
'id' => 37,
'template_id' => 5,
'urutan' => 1,
'Nilai_0' => '<p>Peserta ujian<b> tidak</b> memfasilitasi pasien untuk menceritakan kesakitannya.</p>',
'Nilai_1' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya <b>namun sebagian besar&nbsp; pertanyaan tidak</b>&nbsp; mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>&nbsp;<br><b>Atau </b><br>Melakukan anamnesis secara tidak lengkap atau tidak relevan<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya, <b>namun sebagian kecil&nbsp; pertanyaan tidak</b> mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br><br><br></p>',
'Nilai_3' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya dengan&nbsp; pertanyaan-pertanyaan yang sesuai dengan keluhan pasien untuk mendapatkan informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br>3. RP SOS : Begadang<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
37 => 
array (
'id' => 38,
'template_id' => 5,
'urutan' => 2,
'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
38 => 
array (
'id' => 39,
'template_id' => 5,
'urutan' => 3,
'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
39 => 
array (
'id' => 40,
'template_id' => 5,
'urutan' => 4,
'Nilai_0' => '<p>Peserta ujian tidak mengusulkan tes/prosedur masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian mengusulkan&nbsp; tes/prosedur tidak sesuai masalah klinik pasien</p>',
'Nilai_2' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tidak tepat <br></p>',
'Nilai_3' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tepat <br><br><b>Pemeriksaan Laboratorium : dalam batas normal<br>CT Scan kepala : dalam batas normal</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
40 => 
array (
'id' => 41,
'template_id' => 5,
'urutan' => 5,
'Nilai_0' => '<p>Peserta ujian tidak dapat menentukan diagnosis kerja dan diagnosis banding</p>',
'Nilai_1' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja sebagai diagnosis banding<br><br><b>ATAU </b><br><br>Peserta ujian menetapkan dengan menuliskan diagnosis kerja<br><br></p>',
'Nilai_2' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja dan 1 diagnosis banding</p>',
'Nilai_3' => '<p>Peserta ujian menetapkan dengan menuliskan 1 diagnosis kerja dan 2 diagnosis banding yang lengkap, sesuai dengan masalah klinik pasien<br><br><b>•&nbsp;&nbsp;&nbsp; Diagnosis: BPPV (Benign Paroxismal Positional Vertigo)</b><br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 1: Neuritis vestibuler<br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 2: Meniere’s disease<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
41 => 
array (
'id' => 42,
'template_id' => 5,
'urutan' => 6,
'Nilai_0' => '<p>Peserta ujian tidak melakukan tindakan <br>Atau<br>melakukan tetapi tidak sesuai perintah<br>Atau<br>melakukan tetapi tidak sesuai masalah klinik pasien<br><br></p>',
'Nilai_1' => '<p>Peserta ujian melakukan tindakan yang sesuai perintah atau masalah klinik pasien tetapi tidak lengkap<br><br>Dan Atau <br><br>Tidak menerapkan prinsip septik/ aseptic<br><br></p>',
'Nilai_2' => '<p>Peserta ujian melakukan tindakan yang sesuai masalah klinik pasien, lengkap<br>Tetapi tidak urut dan sistematik<br><br></p>',
'Nilai_3' => '<p>Peserta ujian melakukan tatalaksana non farmakoterapi yang sesuai masalah klinik pasien, lengkap, urut dan sistematik<br><br><b>ATAU</b><br><br>Peserta menyampaikan rencana tatalaksana non farmakoterapi <br><br><b>Non Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Epley Maneuver :<br>•&nbsp;&nbsp;&nbsp; Pasien dilakukan latihan vestibular (vestibular exercise) dengan metode brandDaroff.<br>•&nbsp;&nbsp;&nbsp; Pasien duduk tegak di pinggir tempat tidur dengan kedua tungkai tergantung, dengan kedua mata tertutup baringkan tubuh dengan cepat ke salah satu sisi, pertahankan selama 30 detik. Setelah itu duduk kembali. Setelah 30 detik, baringkan dengan cepat ke sisi lain. Pertahankan selama 30 detik, lalu duduk kembali. Lakukan latihan ini 3 kali pada pagi, siang dan malam hari masing-masing diulang 5 kali serta dilakukan selama 2 minggu atau 3 minggu dengan latihan pagi dan sore hari<br><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
42 => 
array (
'id' => 43,
'template_id' => 5,
'urutan' => 7,
'Nilai_0' => '<p>Peserta ujian tidak memberikan tatalaksana farmakoterapi pada pasien</p>',
'Nilai_1' => '<p>Peserta ujian memilih obat dengan&nbsp; menerapkan <b>beberapa</b>&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br>TETAPI&nbsp; menuliskan resep tidak&nbsp; lengkap<br><br></p>',
'Nilai_3' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br>DAN<br>•&nbsp;&nbsp;&nbsp; menuliskan resep dengan lengkap dan benar.<br><br><b>Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Betahistin tablet 3x6 mg, per oral DAN <br>•&nbsp;&nbsp;&nbsp; Flunarizin tab 2x5 mg<b> DAN</b><br>•&nbsp;&nbsp;&nbsp; Domperidon <b>10 mg 3x1 tab atau</b> Ondansetron 2 x 2mg <br><br><b>Penulisan resep</b><br>R/ Betahistin tab&nbsp; 6 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN<br><br>R/ Ondansetron tab 2 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br>ATAU<br><br>R/ Domperidon tab 10 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN <br><br>R/ Flunarizine tab 5 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br><br><br><br><br>Pro : Tn. X<br>Usia : 40 Tahun<br>Alamat : Cirebon<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
43 => 
array (
'id' => 44,
'template_id' => 5,
'urutan' => 8,
'Nilai_0' => '<p>Peserta ujian sama sekali tidak melakukan komunikasi dan edukasi</p>',
'Nilai_1' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>salah satu</b> prinsip komunikasi dan edukasi <br><br><br></p>',
'Nilai_2' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> point dari&nbsp; prinsip komunikasi dan 2 point dari 3 poin edukasi</p>',
'Nilai_3' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; mampu membina hubungan baik dengan pasien secara verbal non verbal (ramah, terbuka, kontak mata, salam, empati dan hubungan komunikasi dua arah, respon)<br>2.&nbsp;&nbsp;&nbsp; mampu memberikan kesempatan pasien untuk bercerita dan mengarahkan cerita<br>3.&nbsp;&nbsp;&nbsp; mampu untuk melibatkan pasien dalam membuat keputusan klinik, pemeriksaan klinik. <br>4.&nbsp;&nbsp;&nbsp; mampu memberikan penyuluhan yang isinya sesuai dengan masalah&nbsp; pasien <br><br><b>Edukasi :</b><br>1.&nbsp;&nbsp;&nbsp; Penjelasan mengenai penyakit<br>2.&nbsp;&nbsp;&nbsp; Penjelasan mengenai tatacara minum obat<br>3.&nbsp;&nbsp;&nbsp; Penjelasan mengenai pencegahan : Hindari mengubah posisi kepala secara mendadak dan jangan menolehkan kepala pada satu sisi dengan terlalu lama. Lakukan latihan rutin untuk BPPV (manuver epley). Lakukan olahraga rutin, minimal 30 menit setiap hari. Terapkan pola hidup sehat, serta istirahat dan tidur yang cukup. Hindari factor pencetus : kurang tidur<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
44 => 
array (
'id' => 45,
'template_id' => 5,
'urutan' => 9,
'Nilai_0' => '<p>Peserta ujian tidak meminta izin secara lisan dan sama sekali<b> tidak </b>menunjukkan perilaku profesional</p>',
'Nilai_1' => '<p>Meminta izin secara lisan dan menunjukkan <b>1 poin</b> perilaku profesional</p>',
'Nilai_2' => '<p>Meminta izin secara lisan<b> dan</b> menunjukkan <b>2-3 poin </b>perilaku profesional</p>',
'Nilai_3' => '<p>Meminta izin secara lisan dan melakukan di bawah ini secara<b> lengkap:</b><br>1.&nbsp;&nbsp;&nbsp; Menerapkan prinsip Patient Safety (cuci tangan sebelum dan sesudah melakukan pemeriksaan, melakukan setiap tindakan dengan berhati-hati dan teliti sehingga tidak membahayakan pasien dan diri sendiri, memastikan identitas pasien)<br>2.&nbsp;&nbsp;&nbsp; memperhatikan kenyamanan pasien <br>3.&nbsp;&nbsp;&nbsp; menunjukan rasa hormat kepada pasien<br>4.&nbsp;&nbsp;&nbsp; mengetahui keterbatasan dengan merujuk&nbsp; atau melakukan konsultasi bila diperlukan<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:26:36',
'updated_at' => '2025-03-27 07:26:36',
),
45 => 
array (
'id' => 46,
'template_id' => 6,
'urutan' => 1,
'Nilai_0' => '<p>Peserta ujian<b> tidak</b> memfasilitasi pasien untuk menceritakan kesakitannya.</p>',
'Nilai_1' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya <b>namun sebagian besar&nbsp; pertanyaan tidak</b>&nbsp; mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>&nbsp;<br><b>Atau </b><br>Melakukan anamnesis secara tidak lengkap atau tidak relevan<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya, <b>namun sebagian kecil&nbsp; pertanyaan tidak</b> mengarah pada informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br><br><br></p>',
'Nilai_3' => '<p>Peserta ujian memfasilitasi pasien untuk menceritakan kesakitannya dengan&nbsp; pertanyaan-pertanyaan yang sesuai dengan keluhan pasien untuk mendapatkan informasi yang relevan, akurat sebagai berikut<br><br>1. RPS : Onset 2 jam, berputar seluruh kepala, perubahan posisi, menutup mata<br>2. RPD : Riwayat penyakit telinga<br>3. RP SOS : Begadang<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
46 => 
array (
'id' => 47,
'template_id' => 6,
'urutan' => 2,
'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
47 => 
array (
'id' => 48,
'template_id' => 6,
'urutan' => 3,
'Nilai_0' => '<p>Peserta ujian tidak melakukan pemeriksaan fisik yang sesuai dengan masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian melakukan pemeriksaan fisik s<b>esuai masalah klinik pasien</b> dengan tehnik yang tidak tepat<br><br><br></p>',
'Nilai_2' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menggunakan teknik pemeriksaan yang benar tetapi tidak lengkap</p>',
'Nilai_3' => '<p>Melakukan pemeriksaan fisik <b>sesuai masalah klinik pasien</b> dengan menerapkan prinsip sebagai berikut:<br>-&nbsp;&nbsp;&nbsp; Menggunakan teknik pemeriksaan yang benar dan lengkap<br><br><b>Pemeriksaan yang relevan :<br>1)&nbsp;&nbsp;&nbsp; Pem N. III IV VI<br>2)&nbsp;&nbsp;&nbsp; Tes Koordinasi : romberg sign<br>3)&nbsp;&nbsp;&nbsp; Tes khusus : dick halpike test</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
48 => 
array (
'id' => 49,
'template_id' => 6,
'urutan' => 4,
'Nilai_0' => '<p>Peserta ujian tidak mengusulkan tes/prosedur masalah klinik pasien</p>',
'Nilai_1' => '<p>Peserta ujian mengusulkan&nbsp; tes/prosedur tidak sesuai masalah klinik pasien</p>',
'Nilai_2' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tidak tepat <br></p>',
'Nilai_3' => '<p>Peserta ujian mengusulkan prosedur tes yang relevan dan menginterpretasikan hasil dengan tepat <br><br><b>Pemeriksaan Laboratorium : dalam batas normal<br>CT Scan kepala : dalam batas normal</b><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
49 => 
array (
'id' => 50,
'template_id' => 6,
'urutan' => 5,
'Nilai_0' => '<p>Peserta ujian tidak dapat menentukan diagnosis kerja dan diagnosis banding</p>',
'Nilai_1' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja sebagai diagnosis banding<br><br><b>ATAU </b><br><br>Peserta ujian menetapkan dengan menuliskan diagnosis kerja<br><br></p>',
'Nilai_2' => '<p>Peserta ujian menetapkan dengan menuliskan diagnosis kerja dan 1 diagnosis banding</p>',
'Nilai_3' => '<p>Peserta ujian menetapkan dengan menuliskan 1 diagnosis kerja dan 2 diagnosis banding yang lengkap, sesuai dengan masalah klinik pasien<br><br><b>•&nbsp;&nbsp;&nbsp; Diagnosis: BPPV (Benign Paroxismal Positional Vertigo)</b><br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 1: Neuritis vestibuler<br>•&nbsp;&nbsp;&nbsp; Diagnosis Banding 2: Meniere’s disease<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
50 => 
array (
'id' => 51,
'template_id' => 6,
'urutan' => 6,
'Nilai_0' => '<p>Peserta ujian tidak melakukan tindakan <br>Atau<br>melakukan tetapi tidak sesuai perintah<br>Atau<br>melakukan tetapi tidak sesuai masalah klinik pasien<br><br></p>',
'Nilai_1' => '<p>Peserta ujian melakukan tindakan yang sesuai perintah atau masalah klinik pasien tetapi tidak lengkap<br><br>Dan Atau <br><br>Tidak menerapkan prinsip septik/ aseptic<br><br></p>',
'Nilai_2' => '<p>Peserta ujian melakukan tindakan yang sesuai masalah klinik pasien, lengkap<br>Tetapi tidak urut dan sistematik<br><br></p>',
'Nilai_3' => '<p>Peserta ujian melakukan tatalaksana non farmakoterapi yang sesuai masalah klinik pasien, lengkap, urut dan sistematik<br><br><b>ATAU</b><br><br>Peserta menyampaikan rencana tatalaksana non farmakoterapi <br><br><b>Non Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Epley Maneuver :<br>•&nbsp;&nbsp;&nbsp; Pasien dilakukan latihan vestibular (vestibular exercise) dengan metode brandDaroff.<br>•&nbsp;&nbsp;&nbsp; Pasien duduk tegak di pinggir tempat tidur dengan kedua tungkai tergantung, dengan kedua mata tertutup baringkan tubuh dengan cepat ke salah satu sisi, pertahankan selama 30 detik. Setelah itu duduk kembali. Setelah 30 detik, baringkan dengan cepat ke sisi lain. Pertahankan selama 30 detik, lalu duduk kembali. Lakukan latihan ini 3 kali pada pagi, siang dan malam hari masing-masing diulang 5 kali serta dilakukan selama 2 minggu atau 3 minggu dengan latihan pagi dan sore hari<br><br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
51 => 
array (
'id' => 52,
'template_id' => 6,
'urutan' => 7,
'Nilai_0' => '<p>Peserta ujian tidak memberikan tatalaksana farmakoterapi pada pasien</p>',
'Nilai_1' => '<p>Peserta ujian memilih obat dengan&nbsp; menerapkan <b>beberapa</b>&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br></p>',
'Nilai_2' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br><br>TETAPI&nbsp; menuliskan resep tidak&nbsp; lengkap<br><br></p>',
'Nilai_3' => '<p>Peserta ujian memilih obat dengan tepat sesuai&nbsp; seluruh&nbsp; prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; Tepat indikasi<br>2.&nbsp;&nbsp;&nbsp; Tepat dosis<br>3.&nbsp;&nbsp;&nbsp; Tepat sediaan<br>4.&nbsp;&nbsp;&nbsp; Tepat cara pemberian<br>DAN<br>•&nbsp;&nbsp;&nbsp; menuliskan resep dengan lengkap dan benar.<br><br><b>Farmakoterapi :</b><br>•&nbsp;&nbsp;&nbsp; Betahistin tablet 3x6 mg, per oral DAN <br>•&nbsp;&nbsp;&nbsp; Flunarizin tab 2x5 mg<b> DAN</b><br>•&nbsp;&nbsp;&nbsp; Domperidon <b>10 mg 3x1 tab atau</b> Ondansetron 2 x 2mg <br><br><b>Penulisan resep</b><br>R/ Betahistin tab&nbsp; 6 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN<br><br>R/ Ondansetron tab 2 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br>ATAU<br><br>R/ Domperidon tab 10 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 3 dd 1 tab PC<br><br>DAN <br><br>R/ Flunarizine tab 5 mg No X<br>&nbsp;&nbsp;&nbsp;&nbsp; S 2 dd 1 tab PC<br>&nbsp;&nbsp; &nbsp;<br><br><br><br><br>Pro : Tn. X<br>Usia : 40 Tahun<br>Alamat : Cirebon<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
52 => 
array (
'id' => 53,
'template_id' => 6,
'urutan' => 8,
'Nilai_0' => '<p>Peserta ujian sama sekali tidak melakukan komunikasi dan edukasi</p>',
'Nilai_1' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>salah satu</b> prinsip komunikasi dan edukasi <br><br><br></p>',
'Nilai_2' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> point dari&nbsp; prinsip komunikasi dan 2 point dari 3 poin edukasi</p>',
'Nilai_3' => '<p>Peserta ujian menunjukkan kemampuan berkomunikasi dengan menerapkan <b>seluruh</b> prinsip berikut:<br>1.&nbsp;&nbsp;&nbsp; mampu membina hubungan baik dengan pasien secara verbal non verbal (ramah, terbuka, kontak mata, salam, empati dan hubungan komunikasi dua arah, respon)<br>2.&nbsp;&nbsp;&nbsp; mampu memberikan kesempatan pasien untuk bercerita dan mengarahkan cerita<br>3.&nbsp;&nbsp;&nbsp; mampu untuk melibatkan pasien dalam membuat keputusan klinik, pemeriksaan klinik. <br>4.&nbsp;&nbsp;&nbsp; mampu memberikan penyuluhan yang isinya sesuai dengan masalah&nbsp; pasien <br><br><b>Edukasi :</b><br>1.&nbsp;&nbsp;&nbsp; Penjelasan mengenai penyakit<br>2.&nbsp;&nbsp;&nbsp; Penjelasan mengenai tatacara minum obat<br>3.&nbsp;&nbsp;&nbsp; Penjelasan mengenai pencegahan : Hindari mengubah posisi kepala secara mendadak dan jangan menolehkan kepala pada satu sisi dengan terlalu lama. Lakukan latihan rutin untuk BPPV (manuver epley). Lakukan olahraga rutin, minimal 30 menit setiap hari. Terapkan pola hidup sehat, serta istirahat dan tidur yang cukup. Hindari factor pencetus : kurang tidur<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
53 => 
array (
'id' => 54,
'template_id' => 6,
'urutan' => 9,
'Nilai_0' => '<p>Peserta ujian tidak meminta izin secara lisan dan sama sekali<b> tidak </b>menunjukkan perilaku profesional</p>',
'Nilai_1' => '<p>Meminta izin secara lisan dan menunjukkan <b>1 poin</b> perilaku profesional</p>',
'Nilai_2' => '<p>Meminta izin secara lisan<b> dan</b> menunjukkan <b>2-3 poin </b>perilaku profesional</p>',
'Nilai_3' => '<p>Meminta izin secara lisan dan melakukan di bawah ini secara<b> lengkap:</b><br>1.&nbsp;&nbsp;&nbsp; Menerapkan prinsip Patient Safety (cuci tangan sebelum dan sesudah melakukan pemeriksaan, melakukan setiap tindakan dengan berhati-hati dan teliti sehingga tidak membahayakan pasien dan diri sendiri, memastikan identitas pasien)<br>2.&nbsp;&nbsp;&nbsp; memperhatikan kenyamanan pasien <br>3.&nbsp;&nbsp;&nbsp; menunjukan rasa hormat kepada pasien<br>4.&nbsp;&nbsp;&nbsp; mengetahui keterbatasan dengan merujuk&nbsp; atau melakukan konsultasi bila diperlukan<br><br></p>',
'aktif0' => 1,
'aktif1' => 1,
'aktif2' => 1,
'aktif3' => 1,
'bobot' => 1,
'created_at' => '2025-03-27 07:27:19',
'updated_at' => '2025-03-27 07:27:19',
),
));
        
        
    }
}